import {auth,db} from './firebase.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {collection,addDoc,getDocs,query,orderBy,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=id=>document.getElementById(id); let user=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=v=>v?.toDate?new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium',timeStyle:'short'}).format(v.toDate()):'—';
async function load(){const snap=await getDocs(query(collection(db,'users',user.uid,'qualifications'),orderBy('submittedAt','desc'))); if(snap.empty){$('list').innerHTML='<p>No qualifications submitted yet.</p>';return} $('list').innerHTML=snap.docs.map(d=>{const x=d.data();return `<div class="doc"><strong>${esc(x.title)}</strong><br>${esc(x.institution)}${x.qualificationNumber?' • '+esc(x.qualificationNumber):''}<br><span class="badge ${esc(x.status||'pending')}">${esc(x.status||'pending')}</span> <small>${fmt(x.submittedAt)}</small>${x.fileName?`<br>📄 Document reference: ${esc(x.fileName)}`:''}${x.adminNote?`<p><strong>Admin note:</strong> ${esc(x.adminNote)}</p>`:''}</div>`}).join('')}
onAuthStateChanged(auth,async u=>{if(!u){location.href='login.html';return}user=u;try{await load()}catch(e){$('list').textContent='Unable to load qualifications: '+e.message}});
$('form').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;$('submit').disabled=true;$('msg').textContent='Submitting...';try{await addDoc(collection(db,'users',user.uid,'qualifications'),{uid:user.uid,title:$('title').value.trim(),institution:$('institution').value.trim(),qualificationNumber:$('number').value.trim(),issueDate:$('issueDate').value||null,expiryDate:$('expiryDate').value||null,fileName:$('fileName').value.trim(),documentReference:'',status:'pending',submittedAt:serverTimestamp()});$('form').reset();$('msg').textContent='✅ Qualification submitted for verification.';await load()}catch(err){console.error(err);$('msg').textContent='❌ Could not submit qualification: '+err.message}finally{$('submit').disabled=false}});
